version: '3'
services:
  configuration:
    restart: always
    image: configuration
    container_name: configuration
    ports:
      - "8080:8080"

  authentication:
    restart: always
    image: authentication
    container_name: authentication

    depends_on:
      - configuration
    ports:
      - 8081:8081

  authorization:
    restart: unless-stopped
    image: authorization
    container_name: authorization

    depends_on:
      - configuration
    ports:
      - "8082:8082"

  jwt:
    restart: unless-stopped
    image: jwt
    container_name: jwt
    depends_on:
      - configuration
    ports:
      - "8083:8083"
